name: Main Pipeline

on:
  push:
    branches: [main]

jobs:
  test:
    uses: ./.github/workflows/reusable-build-test.yml
    with:
      node_version: "18"

  docker:
    needs: test
    uses: ./.github/workflows/reusable-docker.yml
    with:
      image_name: warriorr/app
    secrets:
      docker_username: ${{ vars.DOCKER_USERNAME }}
      docker_token: ${{ secrets.DOCKER_TOKEN }}


  scan:
    needs: docker
    runs-on: ubuntu-latest

    steps:

      - name: Debug output
        run: echo "IMAGE = ${{ needs.docker.outputs.image_latest }}"

      - name: Scan Docker Image
        uses: aquasecurity/trivy-action@v0.20.0
        with:
            image-ref: ${{ needs.docker.outputs.image_latest }} 
            format: table
            severity: CRITICAL
            exit-code: 1
            output: trivy-report.txt
            
      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        with:
            name: trivy-report
            path: trivy-report.txt

  deploy:
    needs: scan
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Deploy
        run: |
          echo "Deploying:"
          echo "Latest: ${{ needs.docker.outputs.image_latest }}"
          echo "SHA: ${{ needs.docker.outputs.image_sha }}"