name: Build & Test

on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string
      run_tests:
        required: false
        type: boolean
        default: true

jobs:
  build-test:
    runs-on: ubuntu-latest

    outputs:
      test_result: ${{ steps.test.outcome }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        id: test
        if: inputs.run_tests == true
        run: echo "Tests passed"
        env:
          AWS_SECRET_ACCESS_KEY: "anbccw3432_sr"